
import kerbal_part_parser.part_parser
import mks_part_tools
import itertools

def yield_table_rows(inputs, outputs):
    def fmt_value(value):
        if not value:
            return ""
        
        fmt = "%s: %f"
        if value[1] < 0.000001:
            fmt = "%s: %e"

        return fmt % tuple(value)
    
    for i,o in itertools.zip_longest(inputs.items(),outputs.items()):
        yield "| | %s | %s | " % (fmt_value(i), fmt_value(o))   

    
def gen_converters_by_part(parts, converters):
    output = ""
    for part_name, part_converters in sorted(converters.items(), key=lambda x: parts[x[0]]['title']):

        if len(part_converters) > 0:
            output += "\n"
            output += "### %s" % (parts[part_name]['title'])
            
        for converter_name, converter in sorted(part_converters.items()):
            output += "\n"
            output += "| **%s** | Inputs | Outputs |\n" % converter_name
            output += "| --- | --- | --- |\n"

            for row in yield_table_rows(converter['inputs'], converter['outputs']):
                output += row + "\n"

    return output

def gen_resource_sources(mks_parts, sources):
    output = ""
    for resource_name, source_list in sorted(sources.items()):
        output += "#### %s\n" % resource_name
        for source in sorted((mks_parts[source]['title'] for source in source_list)):
            output += " - %s\n" % source
        output += "\n"

    return output

page_template = '''
# Reactions:

A list of all the resource conversations supported by the various modules
(**NOTE: This whole page is generated by https://github.com/nickdavies/ksp_mks_resource_tools**)

## Available Conversions:
%s
## Resource Sources:
Below is a list of what modules produce each resource.
%s
## Resource Dependencies:
Below is a list of what modules require each resource so if your storage is filling up with something
you can lookup what can use it.
%s
'''

if __name__ == "__main__":
    ksp_base_dir = r"C:\Users\e117650\Documents\borlik\personal\games\ksp\KSP_win\\"
    mks_dir = ksp_base_dir + r"GameData\UmbraSpaceIndustries\Kolonization\Parts\\"
    
    data = kerbal_part_parser.part_parser.parse_cfg_dirs(mks_dir, stop_on_error=False)
    mks_parts = mks_part_tools.load_mks_parts(data)

    converters = mks_part_tools.extract_all_converters(mks_parts)
    sources, depends = mks_part_tools.build_resource_lists(converters, ignore={"ElectricCharge"})

    available_conversions = gen_converters_by_part(mks_parts, converters)
    resource_sources = gen_resource_sources(mks_parts, sources)
    resource_depends = gen_resource_sources(mks_parts, depends)
    
    print(page_template % (available_conversions, resource_sources, resource_depends))
    

    
